## EJERCICIOS:

Los siguientes dataframes contienen 3 resultados alternativos a la encuesta del problema anterior. Qué hubiera dicho Ud en cada uno de estos tres casos?

In [ ]:
from scipy.stats import chisquare
import pandas as pd
import numpy as np

In [ ]:
df_01=pd.read_csv('/content/cat_01.csv')
df_02=pd.read_csv('/content/cat_02.csv')
df_03=pd.read_csv('/content/cat_03.csv')

In [ ]:
frec_01 = df_01.value_counts(sort= False)
frec_01

color
azul      25
marron    25
rojo      25
verde     25
Name: count, dtype: int64

In [ ]:
frec_02 = df_02.value_counts(sort= False)
frec_02

color
azul      26
marron    23
rojo      27
verde     24
Name: count, dtype: int64

In [ ]:
frec_03 = df_03.value_counts(sort= False)
frec_03

color
azul      28
marron    22
rojo      30
verde     20
Name: count, dtype: int64

Quiero Demostrar que los colores si influyen en la decisión de las personas

Entonces
- $H_1$: "El color influye en la preferencia de la gente."
y mi Hipotesis nula va a ser
- $H_o$: "El color **no** influye en la preferencia de la gente."

Todo esto aplicado a las 3 encuestas cat_01, cat_02 y cat_03

In [ ]:
df_00=pd.read_csv('/content/cat_esperado.csv')
frec_H0=df_00.value_counts(sort= False)
print(" Valores de la Hipótesis Nula: ")
frec_H0

 Valores de la Hipótesis Nula:

color
azul      25
marron    25
rojo      25
verde     25
Name: count, dtype: int64

Definimos un umbral de un 5%

Convierto en Array a las tablas

In [ ]:
arr_cat01=np.array(frec_01)
arr_cat02=np.array(frec_02)
arr_cat03=np.array(frec_03)

Aplico el Chi cuadrado

In [ ]:
chi2_01, valorP_01 = chisquare(arr_cat01,f_exp=frec_H0)
print(f"\n--- Resultados para frec_01 ---")
print(f"Estadístico Chi-cuadrado: {chi2_01:.4f}")
print(f"P-valor: {valorP_01:.4f}")

--- Resultados para frec_01 ---
Estadístico Chi-cuadrado: 0.0000
P-valor: 1.0000

No hay diferencia entre la hipotesis planteada y la nula, por ende se verifica que el color no influye en la decisión de la gente ya que no hay ninguna evidencia para rechazar $H_o$

In [ ]:
chi2_02, valorP_02 = chisquare(arr_cat02,f_exp=frec_H0)
print(f"\n--- Resultados para frec_02 ---")
print(f"Estadístico Chi-cuadrado: {chi2_02:.4f}")
print(f"P-valor: {valorP_02:.4f}")

--- Resultados para frec_02 ---
Estadístico Chi-cuadrado: 0.4000
P-valor: 0.9402

El valor del estadístico $\chi^2$ es muy bajo, lo que indica que las diferencias entre las frecuencias observadas y esperadas son mínimas.
El p-valor (0.9402) es considerablemente mayor que 0.05, lo que implica que la probabilidad de observar estas diferencias (o mayores) bajo la hipótesis nula es muy alta.

Las pequeñas discrepancias observadas pueden atribuirse al azar muestral, sin evidencia de un desvío real respecto a la distribución esperada.
No se rechaza la hipótesis nula. Las frecuencias observadas son consistentes con las esperadas y no presentan diferencias estadísticamente significativas.

In [ ]:
chi2_03, valorP_03 = chisquare(arr_cat03,f_exp=frec_H0)
print(f"\n--- Resultados para frec_03 ---")
print(f"Estadístico Chi-cuadrado: {chi2_03:.4f}")
print(f"P-valor: {valorP_03:.4f}")

--- Resultados para frec_03 ---
Estadístico Chi-cuadrado: 2.7200
P-valor: 0.4368

En este caso, el estadístico $\chi^2$ es mayor que en los anteriores, lo que indica que existen mayores diferencias entre las frecuencias observadas y esperadas.
Sin embargo, el p-valor (0.4368) sigue siendo superior a 0.05, por lo que estas diferencias no son lo suficientemente grandes como para considerarse estadísticamente significativas.
Aunque hay cierta desviación respecto al modelo esperado, esta puede explicarse por la variabilidad aleatoria propia de los datos y no implica un cambio real en la distribución.
No se rechaza la hipótesis nula. A pesar de observarse mayores diferencias relativas, estas no son estadísticamente significativas.